[package]
name = "arithmetic-coding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitstream-io = "1.2.0"
num-traits = "0.2.14"
thiserror = "1.0.30"

[dev-dependencies]
test-case = "2.0.0"
