[package]
name = "arithmetic-coding"
description = "fast and felxible arithmetic coding library"
version = "0.1.0"
edition = "2021"
license = "MIT"
keywords = ["compression", "encoding", "arithmetic-coding", "lossless"]
categories = ["compression", "encoding", "parsing"]
repository = "https://github.com/danieleades/arithmetic-coding"

[dependencies]
bitstream-io = "1.2.0"
thiserror = "1.0.30"

[dev-dependencies]
fenwick = { version = "1.0.0" }
test-case = "2.0.0"
